table Calendar
	dataCategory: Time
	lineageTag: aadea24f956347858e8f

	column Date
		dataType: dateTime
		formatString: Short Date
		isKey
		lineageTag: d542a790d971420eb74c
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		lineageTag: 83c6a442f7b94e198060
		sourceColumn: Year

	column Month
		dataType: int64
		lineageTag: 87a61a6f1c574580ad8d
		sourceColumn: Month

	column YearMonth
		dataType: string
		lineageTag: 91cd4bf0850346f98bf7
		sourceColumn: YearMonth

	partition Calendar = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("..\..\powerbi_data\Calendar.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"YearMonth", type text}})
			in
				#"Changed Type"
