table Calendar
	dataCategory: Time
	lineageTag: de7819cecf36429fa725

	column Date
		dataType: dateTime
		formatString: Short Date
		isKey
		lineageTag: 0e5e770ca24340e5af66
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		lineageTag: 90f2368c59c84cc1a853
		sourceColumn: Year

	column Month
		dataType: int64
		lineageTag: 40c9ee4c538e4031a440
		sourceColumn: Month

	column YearMonth
		dataType: string
		lineageTag: 8f088f153adb49b5b1f5
		sourceColumn: YearMonth

	partition Calendar = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("..\..\powerbi_data\Calendar.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"YearMonth", type text}})
			in
				#"Changed Type"
