table retailpro_sales
	lineageTag: 2b671052339e4478a47e

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9a4fd6233bfc432d8542
		summarizeBy: none
		sourceColumn: date

	column region
		dataType: string
		lineageTag: a948fafaeeea4d469b1d
		summarizeBy: none
		sourceColumn: region

	column category
		dataType: string
		lineageTag: cebcf1f60831454f9802
		summarizeBy: none
		sourceColumn: category

	column manager
		dataType: string
		lineageTag: 2c7da1027e714478b49e
		summarizeBy: none
		sourceColumn: manager

	column revenue
		dataType: double
		formatString: #,0
		lineageTag: 31bf286621c74becbda7
		sourceColumn: revenue

	column quantity
		dataType: int64
		lineageTag: a1b3227960ec46669c25
		sourceColumn: quantity

	column discount_amount
		dataType: double
		lineageTag: 9343cdaac06a43bfb172
		sourceColumn: discount_amount

	column status
		dataType: string
		lineageTag: d979a5f252f84fdea56b
		sourceColumn: status

	column returns
		dataType: int64
		lineageTag: b09ef75e90a947b69508
		sourceColumn: returns

	column week_start
		dataType: dateTime
		formatString: Short Date
		lineageTag: dc3fb30f8c784871b880
		summarizeBy: none
		sourceColumn: week_start

	column is_return_or_cancel
		dataType: int64
		lineageTag: de623f6fe4c442a8a3b7
		sourceColumn: is_return_or_cancel

	column is_application
		dataType: int64
		lineageTag: fa320cc9c4ac427abe59
		sourceColumn: is_application

	column is_sale
		dataType: int64
		lineageTag: c49ae3c43bca4d489494
		sourceColumn: is_sale

	partition retailpro_sales = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("..\..\powerbi_data\retailpro_sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"date", type date}, {"region", type text}, {"category", type text}, {"manager", type text}, {"revenue", type number}, {"quantity", Int64.Type}, {"discount_amount", type number}, {"status", type text}, {"returns", Int64.Type}, {"week_start", type date}, {"is_return_or_cancel", Int64.Type}, {"is_application", Int64.Type}, {"is_sale", Int64.Type}})
			in
				#"Changed Type"
