table retailpro_sales
	lineageTag: bf20756b4d8642d9a50c

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 67de9f623f784f6dbe9b
		summarizeBy: none
		sourceColumn: date

	column region
		dataType: string
		lineageTag: a6882091c7fb4537befa
		summarizeBy: none
		sourceColumn: region

	column category
		dataType: string
		lineageTag: de48749c463b43ec9dad
		summarizeBy: none
		sourceColumn: category

	column manager
		dataType: string
		lineageTag: 31e526ed8955439fb17f
		summarizeBy: none
		sourceColumn: manager

	column revenue
		dataType: double
		formatString: #,0
		lineageTag: 7ec12cd93b8b47e8b1cb
		sourceColumn: revenue

	column quantity
		dataType: int64
		lineageTag: 2a13125927244a05b66b
		sourceColumn: quantity

	column discount_amount
		dataType: double
		lineageTag: 89aed19f50854325b83b
		sourceColumn: discount_amount

	column status
		dataType: string
		lineageTag: 84f5d174ce404fca8af7
		sourceColumn: status

	column returns
		dataType: int64
		lineageTag: 10d4ae2e15e345509b15
		sourceColumn: returns

	column week_start
		dataType: dateTime
		formatString: Short Date
		lineageTag: 582b1af2501945a7b798
		summarizeBy: none
		sourceColumn: week_start

	column is_return_or_cancel
		dataType: int64
		lineageTag: 776e6af644bd47caa31b
		sourceColumn: is_return_or_cancel

	column is_application
		dataType: int64
		lineageTag: dcaba37f4a7649baa72b
		sourceColumn: is_application

	column is_sale
		dataType: int64
		lineageTag: 5c317a417e3443bb8e05
		sourceColumn: is_sale

	partition retailpro_sales = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("..\..\powerbi_data\retailpro_sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"date", type date}, {"region", type text}, {"category", type text}, {"manager", type text}, {"revenue", type number}, {"quantity", Int64.Type}, {"discount_amount", type number}, {"status", type text}, {"returns", Int64.Type}, {"week_start", type date}, {"is_return_or_cancel", Int64.Type}, {"is_application", Int64.Type}, {"is_sale", Int64.Type}})
			in
				#"Changed Type"
