table UserAccess
	lineageTag: f23a011251bf4a5d9900

	column user_login
		dataType: string
		lineageTag: 9ae586afefa04447ad78
		sourceColumn: user_login

	column role
		dataType: string
		lineageTag: 8a2f739c3fc9471596dd
		sourceColumn: role

	column manager
		dataType: string
		lineageTag: c06a2fb8b88148e9a2ad
		sourceColumn: manager

	column region
		dataType: string
		lineageTag: 839b4d886e624da39ff9
		sourceColumn: region

	partition UserAccess = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("..\..\powerbi_data\UserAccess.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"user_login", type text}, {"role", type text}, {"manager", type text}, {"region", type text}})
			in
				#"Changed Type"
