table UserAccess
	lineageTag: 32ac505ac4f64868a4b2

	column user_login
		dataType: string
		lineageTag: 7cac504acad049b28976
		sourceColumn: user_login

	column role
		dataType: string
		lineageTag: f24976fcd50945599cf3
		sourceColumn: role

	column manager
		dataType: string
		lineageTag: 69a75446c02b4d59acf6
		sourceColumn: manager

	column region
		dataType: string
		lineageTag: 21baa14fd59946fdb32a
		sourceColumn: region

	partition UserAccess = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("..\..\powerbi_data\UserAccess.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"user_login", type text}, {"role", type text}, {"manager", type text}, {"region", type text}})
			in
				#"Changed Type"
